Automaket/Controllers/CarController.cs
using Automarket.Domain.ViewModels.Car;
using Automarket.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Automarket.Controllers
{
    public class CarController : Controller
    {
        private readonly ICarService _carService;

        public CarController(ICarService carService)        
        {
            _carService = carService;
        }

        [HttpGet]
        public IActionResult GetCars()
        {
            var response = _carService.GetCars();
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            return View("Error", $"{response.Description}");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _carService.DeleteCar(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return RedirectToAction("GetCars");
            }
            return View("Error", $"{response.Description}");
        }

        public IActionResult Compare() => PartialView();

        [HttpGet]
        public async Task<IActionResult> Save(int id)
        {
            if (id == 0)
                return PartialView();

            var response = await _carService.GetCar(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return PartialView(response.Data);
            }
            ModelState.AddModelError("", response.Description);
            return PartialView();
        }

        // string Name, string Model, double Speed, string Description, decimal Price, string TypeCar, IFormFile Avatar
        [HttpPost]
        public async Task<IActionResult> Save(CarViewModel model)
        {
            ModelState.Remove("DateCreate");
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {
                    byte[] imageData;
                    using (var binaryReader = new BinaryReader(model.Avatar.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)model.Avatar.Length);
                    }
                    await _carService.Create(model, imageData);
                }
                else
                {
                    await _carService.Edit(model.Id, model);
                }
                return RedirectToAction("GetCars");
            }
            return View();
        }


        [HttpGet]
        public async Task<ActionResult> GetCar(int id, bool isJson)
        {
            var response = await _carService.GetCar(id);
            if (isJson)
            {
                return Json(response.Data);
            }
            return PartialView("GetCar", response.Data);
        }

        [HttpPost]
        public async Task<IActionResult> GetCar(string term, int page = 1, int pageSize = 5)
        {
            var response = await _carService.GetCar(term);
            return Json(response.Data);
        }

        [HttpPost]
        public JsonResult GetTypes()
        {
            var types = _carService.GetTypes();
            return Json(types.Data);
        }
    }
}

Automaket/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Automarket.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index() => View();
    }
}

Automaket/Controllers/UserController.cs
using Automarket.Domain.Entity;
using Automarket.Domain.ViewModels.Account;
using Automarket.Service.Implementations;
using Microsoft.AspNetCore.Mvc;

namespace Automarket.Controllers
{
    public class UserController : Controller
    {

        private readonly UserService _userService;

        public UserController(UserService userService)
        {
            _userService = userService;
        }

        [HttpGet("register")]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost("register")]
        public async Task<ActionResult<User>> Register(RegistrationViewModel model)
        {
            try
            {
                var user = await _userService.RegisterUserAsync(model);
                return RedirectToAction("Index", "Home");
            }
            catch (ApplicationException ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPost("login")]
        public async Task<ActionResult<string>> Login(LoginViewModel model)
        {
            var token = await _userService.AuthenticateAsync(model);
            if (token == null)
            {
                return Unauthorized();
            }
            return RedirectToAction("Index", "Home");
        }

    }
}

Automaket/Views/Car/GetCar.cshtml
@model Automarket.Domain.ViewModels.Car.CarViewModel


@*data:image/jpeg;base64,@Convert.ToBase64String(Model?.Image ?? Array.Empty<byte>())*@
<form>
    <div class="row">
        <div class="col-md-12">
            <img src="https://images.wallpaperscraft.ru/image/single/zdaniia_ogni_svechenie_279703_300x168.jpg"
                 class="img-fluid rounded-start rounded" alt="@Model?.Name">
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="@Model.Name" class="col-form-label"></label>
            <input type="text" class="form-control" asp-for="@Model.Name">
        </div>
        <div class="form-group col-md-4">
            <label asp-for="@Model.Model" class="col-form-label"></label>
            <input class="form-control" asp-for="@Model.Model" />
        </div>
        <div class="form-group col-md-4">
            <label asp-for="@Model.Price" class="col-form-label"></label>
            <input type="text" class="form-control" asp-for="@Model.Price" />
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-12">
            <label asp-for="@Model.Description" class="col-form-label"></label>
            <textarea type="text" class="form-control" asp-for="@Model.Description"></textarea>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="@Model.TypeCar" class="col-form-label"></label>
            <select class="form-control" id="carTypeId2">
                <option value="@Model.TypeCar">@Model.TypeCar</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="@Model.DateCreate" class="col-form-label"></label>
            <input class="form-control" asp-for="@Model.DateCreate" />
        </div>
    </div>
</form>

<style>
    label {
        color: black;
    }
</style>

<script src="~/lib/select2/js/select2.full.min.js"></script>
<script>
    $('#carTypeId2').select2({
       placeholder: "Выберите тип",
       minimumInputLength: 0,
       allowClear: true,
       ajax: {
            type: "POST",
            url: "@Url.Action("GetTypes", "Car")",
            dataType: "json",
            processResults: function (result) {
                return {
                    results: $.map(result, function (val, index) {
                        return {
                            id: index,
                            text: val
                        };
                    }),
                };
            }
        }
    });
</script>

Automaket/Views/Car/GetCars.cshtml
@using Automarket.Domain.ViewModels.Car
@model List<Automarket.Domain.Entity.Car>

@{
    ViewBag.Title = "Список автомобилей";
    Layout = "_Layout";
}

@{
    var cardStyle = "col-md-12";
    if (Model != null)
    {
        switch (Model.Count)
        {
            case 2:
                cardStyle = "col-md-6";
                break;
            default:
                cardStyle = "col-md-4";
                break;
        }
    }
}

<style>
    .card-buttons-group {
        text-align: right;
        padding: 10px;
    }
</style>

<div class="card-buttons-group">
    <button class="btn btn-danger" id='hideCardsId'>Скрыть</button>
    <button class='btn btn-success' id='showCardsId'>Показать</button>
    <button class='btn btn-success' id='addCarId'>Добавить</button>
</div>

<div style="padding: 10px;"></div>
@if (Model == null)
{
    <div class="card col-md-12">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://images.wallpaperscraft.ru/image/single/bmw_fary_podsvetka_137326_1280x720.jpg"
                     class="img-fluid rounded-start rounded">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title text-center">Список машин пуст :(</h5>
                    <p class="card-text">
                        Список пополниться позже, не расстраивайтесь
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div style="padding: 10px;"></div>
    <div class="card text-center">
        <div class="card-header">
            <ul class="nav nav-pills card-header-pills">
                <li class="nav-item">
                    <a class="nav-link active" href="#">Active</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
}
else
{
    <div class="row">
        @foreach (var car in Model)
        {
            <div class="row row-cols-1 @cardStyle text-center">
                <div class="col" style="padding: 10px;">
                    <div class="card">
                        <img src="data:image/jpeg;base64,@Convert.ToBase64String(car.Avatar ?? Array.Empty<byte>())" class="card-img-top" alt="@car.Name">
                        <div class="card-body">
                            <h5 class="card-title">@car.Name</h5>
                            <p class="card-text">@car.Description</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Стоимость: @car.Price ₽</li>
                            <li class="list-group-item">@car.TypeCar</li>
                        </ul>
                        <div class="card-body">
                            <button class="btn btn-primary" onclick="openModal(@car.Id)" asp-action="GetCar" value="@car.Id" asp-route-id="@car.Id"
                                    data-toggle="ajax-modal" data-target="Modal">
                                Открыть
                            </button>
                            @if (User.IsInRole("Admin"))
                            {
                                <button asp-controller="Car" asp-action="Delete" asp-route-id="@car.Id" class="btn btn-danger">Удалить</button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}

<div class="modal fade" id="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Информация об автомобиле</h5>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-close btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                @if (User.IsInRole("Admin"))
                {
                    <button type="button" class="btn btn-primary" id="saveBtn">Сохранить</button>
                }
            </div>
        </div>
    </div>
</div>


@section pageScripts {

    <script>

        function model() {
            const model = {
                name: $('input#Name').val(),
                model: $('input#Model').val(),
                price: $('input#Price').val(),
                description: $('input#Description').val()
            }
            return model;
        };

        $('#saveBtn').on('click', function () {
            $.ajax({
                url: '@Url.Action("Save")',
                type: 'POST',
                data: model(),
            })
        });

        var modal = $('#modal');

        $(".btn-close").click(function () {
            modal.modal('hide');
        });

        function openModal(id) {
            $.ajax({
                type: 'GET',
                url: '/Car/GetCar',
                data: { "id": id },
                success: function (response) {
                    modal.find(".modal-body").html(response);
                    modal.modal('show')
                },
                failure: function () {
                    modal.modal('hide')
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        };

        const hideCardElement = $('#hideCardsId');
        const showCardElement = $('#showCardsId');
        const cardElement = $('.card');

        const interval = 2000;

        hideCardElement.click(function () {
            hideCardElement.hide(interval);
            showCardElement.show(interval);
            cardElement.hide(interval);
        });

        showCardElement.click(function () {
            hideCardElement.show(interval);
            showCardElement.hide(interval);
            cardElement.show(interval);
        });
    </script>
}

Automaket/Views/Car/Save.cshtml
@model Automarket.Domain.ViewModels.Car.CarViewModel
@{
    ViewBag.Title = "Добавление";
    Layout = "_Layout";
}

@{
    var textTitle = Model?.Id == 0 ? "Изменение данных" : "Добавление данных";
}

<div style="padding: 10px;"></div>
<div class="col-md-12">
    <div class="card-body">
        <div class="card card-outline-secondary" style="background-color: white">
            <div class="card-header">
                <h3 class="mb-0 text-center ParagraphHome">@textTitle</h3>
            </div>
            <div class="card-body">
                <form asp-controller="Car" asp-action="Save" enctype="multipart/form-data">
                    <input asp-for="Id" hidden />
                    <div asp-validation-summary="All" style="font-size:23px; font-family:Impact, serif" class="text-danger text-center"></div>
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" type="text">
                    </div>
                    <div class="form-group">
                        <label asp-for="Model"></label>
                        <input asp-for="Model" class="form-control" type="text">
                    </div>
                    <div class="form-group">
                        <label asp-for="Speed"></label>
                        <input asp-for="Speed" class="form-control" type="text">
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text">₽</span>
                        <input asp-for="Price" type="text" class="form-control">
                        <span class="input-group-text">.00</span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TypeCar"></label>
                        <select class="form-control" asp-for="TypeCar" id="carTypeId"></select>
                    </div>
                    <div class="input-group mb-3">
                        <input asp-for="Avatar" class="form-control" type="file">
                    </div>
                    <button class="btn btn-success btn-lg float-right">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>

@section pageScripts
    {
    <script src="~/lib/select2/js/select2.full.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#carTypeId').select2({
                placeholder: "Выберите тип",
                minimumInputLength: 0,
                allowClear: true,
                ajax: {
                    type: "POST",
                    url: "@Url.Action("GetTypes", "Car")",
                    dataType: "json",
                    processResults: function (result) {
                        return {
                            results: $.map(result, function (val, index) {
                                return {
                                    id: index,
                                    text: val
                                };
                            }),
                        };
                    }
                }
            });
        });
    </script>
}

<style>
    label {
        color: black;
    }
</style>

Automaket/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная";
}

<div style="padding: 10px;"></div>
<div class="card col-md-12">
    <div class="card-body">
        <h5 class="card-title text-center">Добро пожаловать на сайт Automarket</h5>
        <p class="card-text">
            На этом сайте вы сможете выбрать подходящую для вас модель автомобиля, посмотреть его характеристики, сравнить
            с другими моделями, а так же можете приобрести этот автомобиль
        </p>
        <p class="card-text"><small class="text-muted">АйтишныйДомосед</small></p>
    </div>
</div>

<div style="padding: 10px;"></div>
<div class="row row-cols-1 row-cols-md-3 g-4">
    @if (User.IsInRole("Admin"))
    {
        <div class="col">
            <div class="card h-100">
                <img src="https://images.wallpaperscraft.ru/image/single/mashina_noch_dozhd_143166_1280x720.jpg" class="card-img-top" />
                <div class="card-body text-center">
                    <h5 class="card-title">Mercedes</h5>
                    <p class="card-text">Mercedes-Benz — торговая марка и одноимённая компания — производитель легковых автомобилей премиального класса, грузовых автомобилей, автобусов и других транспортных средств</p>
                </div>
                <div class="card-footer text-center">
                    <a asp-controller="Car" asp-action="Save" asp-route-id="0" class="card-link">Приобретение</a>
                </div>
            </div>
        </div>
    }
    <div class="col">
        <div class="card h-100">
            <img src="https://images.wallpaperscraft.ru/image/single/bmw_fary_avtomobil_124112_1280x720.jpg" class="card-img-top" />
            <div class="card-body text-center">
                <h5 class="card-title">BMW</h5>
                <p class="card-text">
                    BMW AG — немецкий производитель автомобилей, мотоциклов, двигателей, а также велосипедов
                </p>
            </div>
            <div class="card-footer text-center">
                <a asp-controller="Car" asp-action="GetCars" class="card-link">Список машин</a>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card h-100">
            <img src="https://images.wallpaperscraft.ru/image/single/audi_avtomobil_vid_speredi_130942_1280x720.jpg" class="card-img-top" />
            <div class="card-body text-center">
                <h5 class="card-title">Audi</h5>
                <p class="card-text">Audi AG — немецкая автомобилестроительная компания в составе концерна Volkswagen Group, специализирующаяся на выпуске автомобилей под маркой Audi</p>
            </div>
            <div class="card-footer text-center">
                <a asp-controller="Car" asp-action="" class="card-link">Сравнение</a>
            </div>
        </div>
    </div>
</div>

<div style="padding: 10px;"></div>
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Основные виды кузовов</h5>
        <p class="card-text">
            Тип кузовной конструкции легко определяется по внешнему виду автомобиля. Для каждого класса характерны отличительные черты,
            которые легко обнаружить даже при наличии небольшого опыта. Кроме того, свою роль в классификации играет и способ реализации багажного отделения,
            которое может быть объединено с пассажирским салоном или отделено от него
        </p>
        <a href="#" class="card-link">Card link</a>
        <a href="#" class="card-link">Another link</a>
    </div>
</div>

<div style="padding: 10px;"></div>
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Наибольшим спросом пользуются легковые автомобили со следующими типами кузова</h5>
    </div>
    <ul class="list-group list-group-flush" id="ulListId">
        <li class="list-group-item">Седан — самый распространенный вариант</li>
        <li class="list-group-item">Универсал — семейный автомобиль с большими возможностями</li>
        <li class="list-group-item">Хэтчбек — укороченный вариант универсала</li>
        <li class="list-group-item">Лифтбек — комбинация универсала и седана</li>
        <li class="list-group-item">Купе — машина для ценителей личного пространства</li>
        <li class="list-group-item">Лимузин — показная роскошь</li>
        <li class="list-group-item">Кабриолет всегда притягивает взгляды</li>
        <li class="list-group-item">Внедорожник — повышенная прочность и надежность</li>
    </ul>
    <div class="card-body">
        <button class="btn btn-danger" id="btnHideId">Скрыть</button>
        <button class="btn btn-primary" id="btnShowId">Показать</button>
    </div>
</div>

@section pageScripts
    {
    <script>
        $('#btnHideId').click(function () {
            $('#ulListId').hide(2000);
        });

        $('#btnShowId').click(function () {
            $('#ulListId').show(2000);
        });
    </script>
}

Automaket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <link href="https://raw.githack.com/ttskch/select2-bootstrap4-theme/master/dist/select2-bootstrap4.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/backImage.css" />
    <link rel="stylesheet" href="~/css/menu.css" />
    <link rel="stylesheet" href="~/css/paragraph.css" />
    <link rel="stylesheet" href="~/css/card.css" />
    <link rel="stylesheet" href="~/css/label.css" />
</head>
<body class="backgroundImage">
    <header>
        <nav class="navbar navbar-expand-lg" style="background-color: white;">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><span style="color:black; font-family:Impact; font-size:30px; background-color:white; border-radius:10px;">Automarket</span>@*<img src="~/Img/LSKIcon.jpg" style="width:30px; height: 30px; border-radius: 10px;">*@</a>
            <button class="navbar-toggler badge-light" style="border-radius:10px;" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-caret-down-square-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm4 4a.5.5 0 0 0-.374.832l4 4.5a.5.5 0 0 0 .748 0l4-4.5A.5.5 0 0 0 12 6H4z" />
                </svg>
            </button>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle paragraphLayout active text-black" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-family:'Comic Sans MS'; font-weight: bold;">
                                Аккаунт
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <ul class="nav flex-column paragraphHome">
                                                <li class="nav-item text-center">
                                                    <a class="nav-link active text-white" asp-controller="User" asp-action="Register">
                                                        Регистрация
                                                    </a>
                                                </li>
                                                <li class="nav-item">
                                                    <a class="nav-link active text-white" asp-controller="Account" asp-action="Login">
                                                        Вход
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle paragraphLayout active text-black" href="#" data-toggle="dropdown" style="font-family:'Comic Sans MS'; font-weight: bold;">
                                Авто
                            </a>
                            <div class="dropdown-menu">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <ul class="nav flex-column paragraphHome">
                                                <li class="nav-item text-center">
                                                    <a class="nav-link active text-white" asp-controller="Car" asp-action="GetCars">
                                                        Список
                                                    </a>
                                                </li>
                                                <li class="nav-item text-center">
                                                    <a class="nav-link active text-white" asp-controller="Car" asp-action="Save">
                                                        Добавление
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle paragraphLayout active text-black" href="#" data-toggle="dropdown" style="font-family:'Comic Sans MS'; font-weight: bold;">
                                Админ
                            </a>
                            <div class="dropdown-menu">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <ul class="nav flex-column paragraphHome">
                                                <li class="nav-item text-center">
                                                    <a class="nav-link active text-white" asp-controller="Car" asp-action="Save">
                                                        Добавление
                                                    </a>
                                                </li>
                                                <li class="nav-item text-center">
                                                    <a class="nav-link active text-white" asp-controller="" asp-action="Index">
                                                        Пользователи
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }
                </ul>

                @if (User.Identity.IsAuthenticated)
                {
                    <form method="post" asp-controller="Account" asp-action="Logout">
                        <input class="btn btn-danger rounded" style="font-family:'Comic Sans MS'; font-weight: bold; font-size:20px;" type="submit" value="Выход" />
                    </form>
                }
            </div>
        </nav>
    </header>
    <div class="container-fluid col-xl-12">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    @await RenderSectionAsync("pageScripts", required: false)
</body>
</html>